// <auto-generated />
using System;
using BGAUSS.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BGAUSS.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312081003_AddRemarksToParts")]
    partial class AddRemarksToParts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BGAUSS.Api.Models.Assembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssemblyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Assembli__3214EC071AD246DD");

                    b.HasIndex("ModelId");

                    b.ToTable("Assemblies", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.AssemblyPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssemblyId")
                        .HasColumnType("int");

                    b.Property<string>("Erp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ERP");

                    b.Property<string>("Frt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FRT");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Assembly__3214EC07D9D45470");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("PartId");

                    b.ToTable("AssemblyParts", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Carts__3214EC07A0CBBF40");

                    b.HasIndex("UserId");

                    b.ToTable("Carts", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CartItem__3214EC07D492E4DC");

                    b.HasIndex("PartId");

                    b.HasIndex(new[] { "CartId", "PartId" }, "IX_CartItem_Unique")
                        .IsUnique();

                    b.ToTable("CartItems", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.ModelPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColourId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ModelPar__3214EC071E66AC5A");

                    b.HasIndex("ModelId");

                    b.HasIndex("PartId");

                    b.HasIndex("VariantId");

                    b.ToTable("ModelParts", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_Orders_UserId");

                    b.ToTable("Orders", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderItems_OrderId");

                    b.HasIndex(new[] { "PartId" }, "IX_OrderItems_PartId");

                    b.ToTable("OrderItems", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssemblyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bdp")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("BDP");

                    b.Property<int?>("ColourId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Mrp")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("MRP");

                    b.Property<string>("PartName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("TorqueNm")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Parts__3214EC07953498D7");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("ColourId");

                    b.HasIndex("VariantId");

                    b.ToTable("Parts", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.PartColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PartColo__3214EC07FD323B66");

                    b.HasIndex("ColourId");

                    b.HasIndex("PartId");

                    b.ToTable("PartColours", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.PartImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PartImag__3214EC07E7DB4E9E");

                    b.HasIndex("PartId");

                    b.ToTable("PartImages", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColourId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("VIN");

                    b.HasKey("Id")
                        .HasName("PK__Vehicles__3214EC073BB36037");

                    b.HasIndex("ColourId");

                    b.HasIndex("ModelId");

                    b.HasIndex("VariantId");

                    b.HasIndex(new[] { "Vin" }, "UQ__Vehicles__C5DF234CFF3CF818")
                        .IsUnique()
                        .HasFilter("[VIN] IS NOT NULL");

                    b.ToTable("Vehicles", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColourName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__VehicleC__3214EC074CADA9B6");

                    b.HasIndex("ModelId");

                    b.HasIndex("VariantId");

                    b.ToTable("VehicleColours", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__VehicleM__3214EC07368365C6");

                    b.ToTable("VehicleModels", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("VariantName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__VehicleV__3214EC0703D99E67");

                    b.HasIndex("ModelId");

                    b.ToTable("VehicleVariants", "dbo");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Assembly", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleModel", "Model")
                        .WithMany("Assemblies")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK_Assemblies_Model");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.AssemblyPart", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Assembly", "Assembly")
                        .WithMany("AssemblyParts")
                        .HasForeignKey("AssemblyId")
                        .HasConstraintName("FK__AssemblyP__Assem__05D8E0BE");

                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany("AssemblyParts")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK__AssemblyP__PartI__06CD04F7");

                    b.Navigation("Assembly");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Cart", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Carts__UserId__7B5B524B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.CartItem", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItems__CartI__00200768");

                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany("CartItems")
                        .HasForeignKey("PartId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItems__PartI__01142BA1");

                    b.Navigation("Cart");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.ModelPart", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleModel", "Model")
                        .WithMany("ModelParts")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK__ModelPart__Model__6477ECF3");

                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany("ModelParts")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK__ModelPart__PartI__66603565");

                    b.HasOne("BGAUSS.Api.Models.VehicleVariant", "Variant")
                        .WithMany("ModelParts")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK__ModelPart__Varia__656C112C");

                    b.Navigation("Model");

                    b.Navigation("Part");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Order", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.OrderItem", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany("OrderItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Part", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Assembly", "Assembly")
                        .WithMany("Parts")
                        .HasForeignKey("AssemblyId")
                        .HasConstraintName("FK_Parts_Assembly");

                    b.HasOne("BGAUSS.Api.Models.VehicleColour", "Colour")
                        .WithMany("Parts")
                        .HasForeignKey("ColourId")
                        .HasConstraintName("FK_Parts_Colour");

                    b.HasOne("BGAUSS.Api.Models.VehicleVariant", "Variant")
                        .WithMany("Parts")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK_Parts_Variant");

                    b.Navigation("Assembly");

                    b.Navigation("Colour");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.PartColour", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleColour", "Colour")
                        .WithMany("PartColours")
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PartColours_VehicleColours");

                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany("PartColours")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PartColours_Parts");

                    b.Navigation("Colour");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.PartImage", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany("PartImages")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK__PartImage__PartI__693CA210");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Vehicle", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleColour", "Colour")
                        .WithMany("Vehicles")
                        .HasForeignKey("ColourId")
                        .HasConstraintName("FK__Vehicles__Colour__5CD6CB2B");

                    b.HasOne("BGAUSS.Api.Models.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK__Vehicles__ModelI__5AEE82B9");

                    b.HasOne("BGAUSS.Api.Models.VehicleVariant", "Variant")
                        .WithMany("Vehicles")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK__Vehicles__Varian__5BE2A6F2");

                    b.Navigation("Colour");

                    b.Navigation("Model");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleColour", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleModel", "Model")
                        .WithMany("VehicleColours")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK_Colour_Model");

                    b.HasOne("BGAUSS.Api.Models.VehicleVariant", "Variant")
                        .WithMany("VehicleColours")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("FK_Colour_Variant");

                    b.Navigation("Model");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleVariant", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleModel", "Model")
                        .WithMany("VehicleVariants")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK__VehicleVa__Model__5535A963");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Assembly", b =>
                {
                    b.Navigation("AssemblyParts");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Part", b =>
                {
                    b.Navigation("AssemblyParts");

                    b.Navigation("CartItems");

                    b.Navigation("ModelParts");

                    b.Navigation("OrderItems");

                    b.Navigation("PartColours");

                    b.Navigation("PartImages");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleColour", b =>
                {
                    b.Navigation("PartColours");

                    b.Navigation("Parts");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleModel", b =>
                {
                    b.Navigation("Assemblies");

                    b.Navigation("ModelParts");

                    b.Navigation("VehicleColours");

                    b.Navigation("VehicleVariants");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleVariant", b =>
                {
                    b.Navigation("ModelParts");

                    b.Navigation("Parts");

                    b.Navigation("VehicleColours");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
