// <auto-generated />
using System;
using BGAUSS.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BGAUSS.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310091346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BGAUSS.Api.Models.Assembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssemblyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Assemblies");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.AssemblyPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssemblyId")
                        .HasColumnType("int");

                    b.Property<string>("Erp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("AssemblyId", "PartId")
                        .IsUnique()
                        .HasFilter("[AssemblyId] IS NOT NULL AND [PartId] IS NOT NULL");

                    b.ToTable("AssemblyParts");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("CartId", "PartId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.ModelPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColourId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("PartId");

                    b.HasIndex("VariantId");

                    b.ToTable("ModelParts");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PartId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssemblyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bdp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ColourId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Mrp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PartName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TorqueNm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("ColourId");

                    b.HasIndex("VariantId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.PartImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("PartImages");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColourId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ColourId");

                    b.HasIndex("ModelId");

                    b.HasIndex("VariantId");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasFilter("[Vin] IS NOT NULL");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColourName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("VariantId");

                    b.ToTable("VehicleColours");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("VariantName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("VehicleVariants");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.AssemblyPart", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Assembly", "Assembly")
                        .WithMany("AssemblyParts")
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assembly");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Cart", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.CartItem", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.ModelPart", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleModel", "Model")
                        .WithMany("ModelParts")
                        .HasForeignKey("ModelId");

                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId");

                    b.HasOne("BGAUSS.Api.Models.VehicleVariant", "Variant")
                        .WithMany("ModelParts")
                        .HasForeignKey("VariantId");

                    b.Navigation("Model");

                    b.Navigation("Part");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Order", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.OrderItem", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Part", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Assembly", null)
                        .WithMany("Parts")
                        .HasForeignKey("AssemblyId");

                    b.HasOne("BGAUSS.Api.Models.VehicleColour", null)
                        .WithMany("Parts")
                        .HasForeignKey("ColourId");

                    b.HasOne("BGAUSS.Api.Models.VehicleVariant", null)
                        .WithMany("Parts")
                        .HasForeignKey("VariantId");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.PartImage", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Vehicle", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleColour", "Colour")
                        .WithMany("Vehicles")
                        .HasForeignKey("ColourId");

                    b.HasOne("BGAUSS.Api.Models.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId");

                    b.HasOne("BGAUSS.Api.Models.VehicleVariant", "Variant")
                        .WithMany("Vehicles")
                        .HasForeignKey("VariantId");

                    b.Navigation("Colour");

                    b.Navigation("Model");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleColour", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleModel", "Model")
                        .WithMany("VehicleColours")
                        .HasForeignKey("ModelId");

                    b.HasOne("BGAUSS.Api.Models.VehicleVariant", "Variant")
                        .WithMany("VehicleColours")
                        .HasForeignKey("VariantId");

                    b.Navigation("Model");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleVariant", b =>
                {
                    b.HasOne("BGAUSS.Api.Models.VehicleModel", "Model")
                        .WithMany("VehicleVariants")
                        .HasForeignKey("ModelId");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Assembly", b =>
                {
                    b.Navigation("AssemblyParts");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleColour", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleModel", b =>
                {
                    b.Navigation("ModelParts");

                    b.Navigation("VehicleColours");

                    b.Navigation("VehicleVariants");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("BGAUSS.Api.Models.VehicleVariant", b =>
                {
                    b.Navigation("ModelParts");

                    b.Navigation("Parts");

                    b.Navigation("VehicleColours");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
